name: weather
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  http: ^0.13.4
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2
  flutter_bloc: ^8.0.1
  sqflite: ^2.0.2+1
  equatable: ^2.0.3

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter_icons:
  image_path_android: "images/icon.png"
  image_path_ios: "images/icon.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - images/
    - images/conditions/
    - images/current/
    - assets/

  fonts:
    - family: UbuntuCondensed
      fonts:
        - asset: fonts/UbuntuCondensed-Regular.ttf
    - family: Roboto
      fonts:
      - asset: fonts/Roboto-Regular.ttf
      - asset: fonts/Roboto-Light.ttf
      - asset: fonts/Roboto-Thin.ttf